-- Arrivata · esquema inicial en PostgreSQL
-- Espejo 1:1 de la tabla `prospects` que la app usaba en SQLite.
-- Idempotente: se puede correr varias veces sin romper nada.
--
-- Notas de portabilidad SQLite -> Postgres:
--   * id: AUTOINCREMENT  -> GENERATED BY DEFAULT AS IDENTITY
--         (permite insertar ids explícitos en la migración de datos y seguir
--          autogenerando después; hay que resetear la secuencia al final —
--          lo hace scripts/migrate_sqlite_to_postgres.py).
--   * TEXT: Postgres tiene TEXT nativo, se mantiene igual.
--   * score / score_auto: INTEGER, igual.
--   * is_premium: se deja como SMALLINT 0/1 (NO boolean) a propósito, para que
--     el código (`1 if data['is_premium'] else 0`) y los tests (esperan 0 / 1)
--     no cambien de comportamiento.
--   * lat / lng: DOUBLE PRECISION (NO REAL: REAL es float de 4 bytes y perdería
--     precisión en coordenadas como -34.5939654).
--   * created_at / updated_at: TEXT con timestamp ISO, igual que en SQLite
--     (las plantillas hacen `created_at[:10]`, necesitan string).

CREATE TABLE IF NOT EXISTS prospects (
    id                INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name              TEXT NOT NULL,
    type              TEXT DEFAULT '',
    neighborhood      TEXT DEFAULT '',
    zone              TEXT DEFAULT 'CABA',
    address           TEXT DEFAULT '',
    phone             TEXT DEFAULT '',
    email             TEXT DEFAULT '',
    instagram         TEXT DEFAULT '',
    website           TEXT DEFAULT '',
    products_interest TEXT DEFAULT '',
    score             INTEGER DEFAULT 5,
    score_auto        INTEGER DEFAULT 5,
    is_premium        SMALLINT DEFAULT 0,
    contact_status    TEXT DEFAULT 'Pendiente',
    notes             TEXT DEFAULT '',
    lat               DOUBLE PRECISION,
    lng               DOUBLE PRECISION,
    geocode_status    TEXT DEFAULT '',
    created_at        TEXT DEFAULT to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS'),
    updated_at        TEXT DEFAULT to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

-- La app busca / hace upsert por (name, neighborhood).
CREATE INDEX IF NOT EXISTS idx_prospects_name_neighborhood
    ON prospects (name, neighborhood);
