-- Arrivata · migración incremental
-- Tabla de usuarios admin (login individual, Flask-Login). La contraseña
-- compartida de solo lectura NO vive acá — es la env var VIEWER_PASSWORD.
-- Idempotente: CREATE TABLE/INDEX IF NOT EXISTS + guard; se puede re-correr.

CREATE TABLE IF NOT EXISTS users (
    id            INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username      TEXT NOT NULL,
    password_hash TEXT NOT NULL,
    role          TEXT NOT NULL DEFAULT 'admin',
    created_at    TEXT DEFAULT to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

CREATE UNIQUE INDEX IF NOT EXISTS idx_users_username ON users (username);

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conname = 'users_role_chk'
          AND conrelid = 'users'::regclass
    ) THEN
        ALTER TABLE users ADD CONSTRAINT users_role_chk
            CHECK (role IN ('admin', 'viewer'));
    END IF;
END $$;
