-- Arrivata · migración incremental
-- Orden personal de visitas: cada usuario admin puede reordenar a mano su
-- propia lista de prospectos en el dashboard ("Mi orden"), independiente del
-- de los demás usuarios y del orden automático por score_auto.
-- Idempotente: CREATE TABLE/INDEX IF NOT EXISTS; se puede re-correr.

CREATE TABLE IF NOT EXISTS visit_order (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id     INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    prospect_id INTEGER NOT NULL REFERENCES prospects(id) ON DELETE CASCADE,
    position    INTEGER NOT NULL,
    updated_at  TEXT DEFAULT to_char(now(), 'YYYY-MM-DD"T"HH24:MI:SS')
);

-- Clave única (user_id, prospect_id): un usuario no puede tener dos
-- posiciones para el mismo prospecto.
CREATE UNIQUE INDEX IF NOT EXISTS idx_visit_order_user_prospect
    ON visit_order (user_id, prospect_id);

-- Para reconstruir el orden completo de un usuario rápido (ORDER BY position).
CREATE INDEX IF NOT EXISTS idx_visit_order_user ON visit_order (user_id, position);
